services:
  web:
    image: nginx:alpine
    container_name: fe_web
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: fe_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fe_phpmyadmin
    ports:
      - "8081:80"
    environment:
       PMA_HOST: mysql
       PMA_PORT: 3306
    depends_on:
      - mysql
    restart: unless-stopped
  api:
    build: ./api
    container_name: fe_api
    environment:
      DB_HOST: mysql
      DB_USER: demo
      DB_PASSWORD: demo1234
      DB_NAME: demo_db
    depends_on:
      - mysql
    restart: unless-stopped
volumes:
  mysql_data:
